parameters:
#    codebender_compiler.example.class: Codebender\CompilerBundle\Example
    buildercompiler_handler.class:	Codebender\CompilerBundle\Handler\BuilderCompilerHandler
    compiler_handler.class:	Codebender\CompilerBundle\Handler\CompilerHandler
    utility_handler.class:	Codebender\CompilerBundle\Handler\UtilityHandler
    preprocessing_handler.class:	Codebender\CompilerBundle\Handler\PreprocessingHandler
    postprocessing_handler.class:	Codebender\CompilerBundle\Handler\PostprocessingHandler
    deletion_handler.class:	Codebender\CompilerBundle\Handler\DeletionHandler

services:
#    codebender_compiler.example:-
#        class: %codebender_compiler.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    buildercompiler_handler:
        class:			"%buildercompiler_handler.class%"
        arguments:		["@preprocessing_handler", "@postprocessing_handler", "@utility_handler", "@compiler_logger", "%temp_dir%/%objdir%"]
    compiler_handler:
        class:			"%compiler_handler.class%"
        arguments:		["@preprocessing_handler", "@postprocessing_handler", "@utility_handler", "@compiler_logger", "%temp_dir%/%objdir%"]
    utility_handler:
        class:			"%utility_handler.class%"
    preprocessing_handler:
        class:			"%preprocessing_handler.class%"
    postprocessing_handler:
        class:			"%postprocessing_handler.class%"
    deletion_handler:
        class:			"%deletion_handler.class%"
        arguments:		["%temp_dir%/%objdir%"]
    compiler_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [cmplr_log]
        calls:
            - [pushHandler, [@compiler_log_handler]]
    compiler_log_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/compiler.log]
